language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: 3kBzxSjPrBXzTun1JJM7ixDDszPQsXwtBFm6rI/ISVmSeTQ1uUB+XJ2xrFF30cUmHMB9UdGD3AxqoCEbA8NMlzmq9s5GEYWtSmeah16G10TPbl7j7Qw3xDvspzKp1Ccr4oH/GVIGBvCjt0pDnnIexVZ9qDiTK4QCX34HLxMbWXSmH8xNQun3sAyoV1otqvU43Qk0n2s5IsHdhT559+yTzbO44SYBJyQ9XdyWfUmos2/BX2ocCRtwjAlvKu/N01c9afv65p9Pqlc13CCkTo8yCTkhqFgQwQTppJkM2mLtH5JEx37IcVLW526Mz7Wl1noY5uqYS+doEYjUVNTZ0bKvSJYieodH1Yp693Agy4V4sLPh6N8+LSici17UX1GNn1mLpGQsG98CLMhCSDmfHrS9+cw4sLJ4IiRMnCBie6PEjyJV6zaIYcjaGQnzx06sD+28vIKyAKtYY6Lgviv/Ek+S7xYfVYYy2Q+K3ubHZtzwDbQD0zpJ6wnR6iDNgo3oS5LXA5hobxmHZbuHcq76uNcd4zCqiWU3oI7LYEphAjAGSGVAxs2PhmmK+Jpbz7/mOY7ZgEND0ptigXo9QKoY5R3y3J4NISJHT9SMSKjl73LtUg9ZEmJy9it5NVZFCl2ZqxJVPnC+dtK2RGJVmwcyB+GMGCgjcdAV5ibHbuXqQVWGifg=
  app: web-push-generator
  local_dir: build
  on:
    branch: master
