language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: RNh6xtWdVGY9u2plXZSbXYs88OY0f1cAJndCYAkAXWIUJTLUiHx9nhtIwprDfGXDwI9jRyxQne9CR1KtnZT+QOhsy3T4kw8AhhcsOLiSPSnuFN3NxJqsaJ0w0XtySCKYwMqZYVIBiqXgFrNRQUkJNhTYKFxQBAo9XULlqrig9gs6TzrvZetXuwelqg90i++754mZeW+oPrKsoImIEx6VFGd7Jfk/yG2G+pOVFmrx+rxfp346ZXJV2IP371hWBpAwTs2a7y8uxO4erUY337HRRING+SigI5IJA5v7LQZgOVzgIc+wByke9bsvxSYRwydIVx800caW2cDVlndEwflmz3TChX84pYW3ql80tWR58RjQp9q66C7ewMng+2sOgLbU81ObKZ5nrr8cUFrypbLu1A+dV9MWwqzhofJ8sjtnhOjHRM8PrZYsVfgODdyT9yeXqqiifHH8YTnoRf1f59b6ojsu0FI2T5BLMPwubkaS948ADap8y32PTwCBVgmdqS+vB8S3eyOtgzArfzYHClAwxTjvNyyY/Ct7Iv839l6U/unoVjED86Wb2TR0/oOY2YrQHI0OvVTef1GcCe2ZhQ+IKVzoi0CnFOp7NrNsCGhdOExgUfDB4rcGRRugOtepg2uKn+xclLcgWHSlqHJo0/Dvf3/7/WPFMQuAPKAov6ixuOk=
  app: web-push-generator
  local_dir: build
  on:
    branch: master
